stages:
  - build
  - test
  - deploy

build-project:
  stage: build
  image: docker.io/node:latest
  variables:
    VERCEL_ORG_ID: $VERCEL_ORG_ID$
    VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID$
    NODE_MAJOR: 20
    SHELL: "bash"
  script:
    - curl -fsSL https://get.pnpm.io/install.sh | env PNPM_VERSION=10.0.0 sh -
    - source /root/.bashrc
    - pnpm install
    - npx vercel env pull .env.local --yes --environment=production --token=$VERCEL_TOKEN$
    - pnpm tsx lib/db/migrate
    - pnpm vercel build --token=$VERCEL_TOKEN$
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
  tags:
    - shared

deploy-to-vercel:
  stage: deploy
  image: docker.io/node:latest
  variables:
    VERCEL_ORG_ID: $VERCEL_ORG_ID$
    VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID$
  script:
    - npm vercel deploy --prebuilt --token=$VERCEL_TOKEN$
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
  tags:
    - shared

